(()=>{'use strict';
const topics={university:['University','#176a6c'],city:['City & neighborhoods','#b36a29'],transport:['Transport','#586ba3'],institutions:['Medical / ESF / East Adams','#8b526b'],housing:['Campus housing reference','#568442']};
const data=window.STUDY_SITES,geo=window.STUDY_NEIGHBORHOODS;if(!data||!window.L)return;
const features=data.features,instances={},occurrences={};const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sectionNames={university:'Syracuse University',city:'City & neighborhood plans',transport:'Transport connections',institutions:'Hospitals, ESF & East Adams',connections:'Shared timeline',drawings:'Drawing source guide'};
// Longest names first; never overwrite citations, links or original words.
const sorted=features.flatMap(f=>f.properties.terms.map(t=>({term:t,f}))).sort((a,b)=>b.term.length-a.term.length);
let para=0;const cross=(id,section,node)=>{node.id ||= 'place-reading-'+(++para);(occurrences[id] ||= []).push({id:node.id,section,length:node.textContent.length});};
for(const sec of document.querySelectorAll('main > section')){
 if(sec.id==='start')continue;
 const nodes=[];const w=document.createTreeWalker(sec,NodeFilter.SHOW_TEXT,{acceptNode(n){return n.parentElement.closest('a,script,style,summary,details,.study-atlas,h1,h2,h3,figcaption')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}});while(w.nextNode())nodes.push(w.currentNode);
 for(const n of nodes){const txt=n.textContent;let matches=[];for(const item of sorted){let at=0;while((at=txt.indexOf(item.term,at))>=0){const end=at+item.term.length;if(!matches.some(m=>at<m.end&&end>m.at)&&!(/[\p{L}]/u.test(txt[at-1]||'')||/[\p{L}]/u.test(txt[end]||'')))matches.push({at,end,...item});at=end;}}
 if(!matches.length)continue;matches.sort((a,b)=>a.at-b.at);let frag=document.createDocumentFragment(),last=0;for(const m of matches){frag.append(txt.slice(last,m.at));const a=document.createElement('a');a.className='site-link';a.href='#atlas-'+(instances[sec.id]||['university','city','transport','institutions'].includes(sec.id)?sec.id:'overall');a.dataset.site=m.f.properties.id;a.dataset.section=sec.id;a.textContent=txt.slice(m.at,m.end);a.title='Locate '+m.f.properties.name+' on the study map';frag.append(a);cross(m.f.properties.id,sec.id,n.parentElement.closest('p,li,td')||n.parentElement);last=m.end;}frag.append(txt.slice(last));n.replaceWith(frag);}
}
// Register authored acquisition-table links as reading destinations too.
for(const a of document.querySelectorAll('.site-link[data-site]')){const sec=a.closest('section');if(!sec)continue;const node=a.closest('p,li,td')||a.parentElement;if(!(occurrences[a.dataset.site]||[]).some(o=>o.id===node.id&&node.id))cross(a.dataset.site,sec.id,node);}
const money=v=>v==null?'Not established':'$'+Number(v).toLocaleString('en-US');
function acquisitionFacts(p){const a=p.acquisition;if(!a)return '';return `<div class="map-acquisition"><h4>Acquisition evidence</h4><p><strong>Municipal sale entry:</strong> ${esc(a.saleDate||'See detailed register')}<br><strong>Reported consideration:</strong> ${esc(money(a.consideration?.amount))}<br><strong>Assessment (${esc(a.assessment?.year||'date unresolved')}):</strong> ${esc(money(a.assessment?.amount))}</p><p>${esc(a.consideration?.basis||'')}. ${esc(a.consideration?.status||'')}</p><p>Assessment is not an appraisal or market worth. ${esc(a.assessment?.basis||'')}</p>${a.rationale?.stated?`<p><strong>Published reason:</strong> ${esc(a.rationale.stated)}</p>`:'<p>A purchase-time reason is not established.</p>'}<a href="interactive/acquisitions.html">Read the acquisition evidence and limits →</a></div>`;}
function available(section){return features.filter(f=>section==='overall'||(occurrences[f.properties.id]||[]).some(o=>o.section===section)||f.properties.topic===section)}
function install(section,title){const sec=document.getElementById(section==='overall'?'start':section);if(!sec)return;const el=document.createElement('div');el.className='study-atlas';el.id='atlas-'+section;el.innerHTML=`<div class="atlas-heading"><h2>${title}</h2><p>Explore the places behind the briefing. Click an outline for its story, or a linked place name in the text to locate it here.</p></div><div class="atlas-controls"><label>Show <select class="atlas-topic"><option value="all">All relevant sites</option>${Object.entries(topics).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></label><label>Status <select class="atlas-status"><option value="all">All statuses</option><option value="acquired">Acquisitions / gifts</option><option value="proposal">Plans / work underway</option><option value="existing">Existing references</option></select></label><input type="search" class="atlas-search" placeholder="Find a place or address" aria-label="Find a place or address"><select class="atlas-picker" aria-label="Choose a mapped place"><option value="">Choose a place…</option></select><button class="atlas-reset">Reset view</button><button class="atlas-expand">Expand map</button><label><input type="checkbox" class="atlas-boundaries" checked>Area boundaries</label><label><input type="checkbox" class="atlas-housing">Housing context</label></div><div class="atlas-layout"><div class="atlas-map" aria-label="${title}" tabindex="0"></div><aside class="atlas-details" aria-live="polite"><h3>Start with a place</h3><p>Official neighborhoods sit behind the sites. Medical, academic, commercial and housing areas overlap that geography; their orientation outlines are labelled separately.</p><p>Buildings and parcels are outlines; transport discussions follow street lines. A location outline is not a future design footprint.</p></aside></div><div class="atlas-legend">${Object.entries(topics).map(([k,v])=>`<span><i style="--swatch:${v[1]}"></i>${v[0]}</span>`).join('')}<span>Dashed site outlines = proposal / discussion; thin area outlines = geographic context</span></div><div class="atlas-footer"><span class="atlas-count"></span> · Geometry dates and qualifications are available for each place.<br><a href="#" class="atlas-svg">Download this view as SVG</a><a href="interactive/sites.geojson" download>Download mapped geometry</a><a href="interactive/map-guide.html">Map guide & sources</a></div>`;
 const heading=sec.querySelector('h1');heading.insertAdjacentElement('afterend',el);const map=L.map(el.querySelector('.atlas-map'),{scrollWheelZoom:false,zoomSnap:.5}).setView([43.037,-76.127],14);L.control.scale({imperial:true,metric:true}).addTo(map);
 let errors=0;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',crossOrigin:true});tiles.on('tileerror',()=>{if(++errors===3){const msg=document.createElement('div');msg.className='atlas-no-tiles';msg.textContent='Street basemap unavailable. Study outlines and place links remain usable.';el.querySelector('.atlas-map').append(msg);}});tiles.addTo(map);
 const boundaries=L.layerGroup(),labels=L.layerGroup();geo.features.forEach(f=>{const n=f.properties.name,core=f.properties.role==='core';const colors={'University Hill':'#6b9ba5','University Neighborhood':'#bba57a',Westcott:'#9d9aaf','Outer Comstock':'#b4b9a3','South Campus':'#9daf93'};let l=L.geoJSON(f,{interactive:false,style:{color:colors[n]||'#778879',weight:core?2.4:1.2,dashArray:core?'6 3':'2 5',fillColor:colors[n]||'#778879',fillOpacity:core?.12:.035}});l.addTo(boundaries);const c=l.getBounds().getCenter();L.marker(c,{interactive:false,icon:L.divIcon({className:'district-label',html:esc(n)+(core?'':'<br><small>outside core</small>'),iconSize:[130,30],iconAnchor:[65,15]})}).addTo(labels);});(window.STUDY_PLACE_AREAS?.features||[]).forEach(f=>{const l=L.geoJSON(f,{style:{color:'#8c8769',weight:1,dashArray:'2 4',fillColor:'#d4c99e',fillOpacity:.03}});l.bindTooltip(f.properties.name+' — '+f.properties.description);l.addTo(boundaries);L.marker(l.getBounds().getCenter(),{interactive:false,icon:L.divIcon({className:'place-label',html:esc(f.properties.name)+'<br><small>orientation area</small>',iconSize:[150,26],iconAnchor:[75,13]})}).addTo(labels);});boundaries.addTo(map);labels.addTo(map);map.on('zoomend',()=>{el.querySelectorAll('.place-label').forEach(x=>x.style.display=map.getZoom()>=14.5?'':'none')});
 const layers=L.layerGroup().addTo(map),fs=available(section),state={el,map,layers,fs,visible:[],selected:null};instances[section]=state;
 function draw(){layers.clearLayers();const q=el.querySelector('.atlas-search').value.toLowerCase(),topic=el.querySelector('.atlas-topic').value,housing=el.querySelector('.atlas-housing').checked,status=el.querySelector('.atlas-status').value;state.visible=fs.filter(f=>{const p=f.properties;const acquired=/Acquired|Gift/i.test(p.status),planned=/propos|planned|under way|concept|corridor|future planning/i.test(p.status);return (status==='all'||status==='acquired'&&acquired||status==='proposal'&&!acquired&&planned||status==='existing'&&!acquired&&!planned)&&(p.topic!=='housing'||housing||topic==='housing')&&(topic==='all'||p.topic===topic)&&(`${p.name} ${(p.addresses||[]).join(' ')} ${p.summary}`.toLowerCase().includes(q));});const picker=el.querySelector('.atlas-picker');picker.innerHTML='<option value="">Choose a place…</option>'+state.visible.slice().sort((a,b)=>a.properties.name.localeCompare(b.properties.name)).map(f=>`<option value="${f.properties.id}">${esc(f.properties.name)}</option>`).join('');state.visible.forEach(f=>{const p=f.properties,c=topics[p.topic][1],dashed=/propos|planned|under way|concept|corridor/i.test(p.status);const l=L.geoJSON(f,{style:{color:c,weight:p.id===state.selected?5:2.5,opacity:.95,fillOpacity:p.id===state.selected?.38:.2,dashArray:dashed?'7 4':null},pointToLayer:(f,latlng)=>L.marker(latlng,{icon:L.divIcon({className:'site-approx',html:`<span style="color:${c};font-size:23px">◇</span>`,iconSize:[22,22],iconAnchor:[11,11]})})}).addTo(layers);l.bindTooltip(p.name,{sticky:true});l.on('click',()=>select(p.id,false));f._layer=l;});el.querySelector('.atlas-count').textContent=state.visible.length+' mapped places';}
 function reset(){const core=geo.features.filter(f=>f.properties.role==='core');if(section==='overall')map.fitBounds(L.geoJSON(core).getBounds(),{padding:[18,18]});else{let active=state.visible.filter(f=>f.properties.topic!=='housing'&&!['euclid','westcott-street','drumlins'].includes(f.properties.id));if(active.length)map.fitBounds(L.geoJSON(active).getBounds(),{padding:[24,24],maxZoom:15});}}
 function select(id,zoom=true){const f=features.find(f=>f.properties.id===id);if(!f)return;state.selected=id;el.querySelector('.atlas-topic').value='all';el.querySelector('.atlas-status').value='all';el.querySelector('.atlas-search').value='';if(f.properties.topic==='housing')el.querySelector('.atlas-housing').checked=true;if(!fs.includes(f))fs.push(f);draw();el.querySelector('.atlas-picker').value=id;const p=f.properties;const links=(occurrences[id]||[]).slice().sort((a,b)=>b.length-a.length).filter((o,i,a)=>a.findIndex(x=>x.section===o.section)===i).sort((a,b)=>(a.section===section?-1:1));el.querySelector('.atlas-details').innerHTML=`<span class="site-status">${esc(p.status)}</span><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p>${p.addresses.length?`<p><strong>Location</strong><br>${p.addresses.map(esc).join('<br>')}</p>`:''}${acquisitionFacts(p)}${links.map(o=>`<a class="read-site" href="#${o.id}" data-reading="${o.id}">Read: ${esc(sectionNames[o.section]||o.section)} →</a>`).join('')}<details><summary>Geometry, sources and limits</summary><p>${esc(p.geometryNote)}</p>${p.parcelIds.length?'<p>Parcel IDs: '+p.parcelIds.map(esc).join(', ')+'</p>':''}${(p.recordSources||[]).slice(0,4).map(u=>`<p><a href="${esc(u)}" target="_blank" rel="noopener">Open property / acquisition source</a></p>`).join('')}${p.geometrySources.map(u=>`<p><a href="${esc(u)}" target="_blank" rel="noopener">Open geometry source</a></p>`).join('')}</details>`;el.querySelector('.atlas-details').scrollTop=0;if(zoom)map.fitBounds(f._layer.getBounds?f._layer.getBounds():L.latLngBounds(f._layer.getLayers()[0].getLatLng(),f._layer.getLayers()[0].getLatLng()),{padding:[55,55],maxZoom:17.5});}
 state.select=select;state.draw=draw;state.reset=reset;
 el.querySelector('.atlas-status').addEventListener('change',()=>{draw();reset()});el.querySelector('.atlas-topic').addEventListener('change',()=>{draw();reset()});el.querySelector('.atlas-search').addEventListener('input',draw);el.querySelector('.atlas-housing').addEventListener('change',draw);el.querySelector('.atlas-picker').addEventListener('change',e=>{if(e.target.value)select(e.target.value)});el.querySelector('.atlas-reset').onclick=()=>{el.querySelector('.atlas-topic').value='all';el.querySelector('.atlas-status').value='all';el.querySelector('.atlas-search').value='';state.selected=null;draw();reset()};el.querySelector('.atlas-boundaries').onchange=e=>{for(const l of [boundaries,labels])e.target.checked?l.addTo(map):map.removeLayer(l)};el.querySelector('.atlas-expand').onclick=()=>{const x=el.querySelector('.atlas-layout');if(document.fullscreenElement)document.exitFullscreen();else if(x.requestFullscreen)x.requestFullscreen();};el.querySelector('.atlas-svg').onclick=e=>{e.preventDefault();exportSVG(state)};new ResizeObserver(()=>map.invalidateSize()).observe(el.querySelector('.atlas-map'));draw();reset();}
function exportSVG(s){const w=1100,h=760,b=s.map.getBounds(),to=xy=>{const p=s.map.project(L.latLng(xy[1],xy[0]),16),nw=s.map.project(b.getNorthWest(),16),se=s.map.project(b.getSouthEast(),16);return[(p.x-nw.x)/(se.x-nw.x)*w,(p.y-nw.y)/(se.y-nw.y)*(h-110)]};function path(g){const seq=cs=>cs.map((c,i)=>(i?'L':'M')+to(c).map(n=>n.toFixed(2)).join(',')).join(' ');if(g.type==='Polygon')return g.coordinates.map(cs=>seq(cs)+' Z').join(' ');if(g.type==='MultiPolygon')return g.coordinates.map(c=>path({type:'Polygon',coordinates:c})).join(' ');if(g.type==='LineString')return seq(g.coordinates);if(g.type==='MultiLineString')return g.coordinates.map(seq).join(' ');return ''}let content=geo.features.map(f=>`<path d="${path(f.geometry)}" fill="none" stroke="#a3b0a6" stroke-dasharray="5 4"/>`).join('');s.visible.forEach(f=>{const c=topics[f.properties.topic][1];content+=`<path d="${path(f.geometry)}" fill="${/Polygon/.test(f.geometry.type)?c:'none'}" fill-opacity=".18" stroke="${c}" stroke-width="2"/>`;const center=L.geoJSON(f).getBounds().getCenter(),pt=to([center.lng,center.lat]);if(pt[0]>=0&&pt[0]<w&&pt[1]>=0&&pt[1]<h-110)content+=`<text x="${pt[0]}" y="${pt[1]}" font-size="10" fill="${c}" stroke="white" stroke-width="2" paint-order="stroke">${esc(f.properties.name)}</text>`;});const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="#fffdf6"/><g font-family="Arial">${content}<rect y="${h-105}" width="${w}" height="105" fill="#fffdf6"/><text x="20" y="${h-78}" font-size="20">University Hill — briefing location reference</text><text x="20" y="${h-52}" font-size="12">September 7, 2026 • City neighborhood / parcel layers and OpenStreetMap contributors</text><text x="20" y="${h-30}" font-size="12">Outlines locate discussion; not a survey, ownership certification or future design. Source dates differ.</text></g></svg>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download='university-hill-study-map.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
install('overall','The study area: places, plans and connections');for(const [k,t] of Object.entries(sectionNames).slice(0,4))install(k,t+' — map');
document.addEventListener('click',e=>{const a=e.target.closest('.site-link');if(a){e.preventDefault();const section=['university','city','transport','institutions'].includes(a.dataset.section)?a.dataset.section:'overall';const s=instances[section];s.el.scrollIntoView({behavior:'smooth',block:'start'});s.select(a.dataset.site);setTimeout(()=>s.map.invalidateSize(),350);}const r=e.target.closest('[data-reading]');if(r){e.preventDefault();const p=document.getElementById(r.dataset.reading);for(let d=p.closest('details');d;d=d.parentElement.closest('details'))d.open=true;p.scrollIntoView({behavior:'smooth',block:'center'});p.classList.add('map-reading-focus');p.setAttribute('tabindex','-1');p.focus({preventScroll:true});history.replaceState(null,'','#'+p.id);setTimeout(()=>p.classList.remove('map-reading-focus'),4500);}});
// Every discussion with mapped mentions gets a quick focus control, without duplicating map canvases.
for(const sec of document.querySelectorAll('main > section')){if(!instances[sec.id])continue;for(const heading of [...sec.querySelectorAll('h2,h3')].filter(h=>!h.closest('.study-atlas'))){let n=heading.nextElementSibling,ids=[];while(n&&!/^H[123]$/.test(n.tagName)){ids.push(...[...n.querySelectorAll('.site-link')].map(x=>x.dataset.site));n=n.nextElementSibling;}ids=[...new Set(ids)];if(!ids.length)continue;const b=document.createElement('button');b.className='atlas-subfocus';b.textContent='Locate these '+ids.length+' place'+(ids.length===1?'':'s');b.onclick=()=>{const s=instances[sec.id];s.el.scrollIntoView({behavior:'smooth'});s.el.querySelector('.atlas-topic').value='all';s.el.querySelector('.atlas-status').value='all';s.el.querySelector('.atlas-search').value='';s.draw();s.map.fitBounds(L.geoJSON(features.filter(f=>ids.includes(f.properties.id))).getBounds(),{padding:[35,35],maxZoom:16});s.select(ids[0],false)};heading.insertAdjacentElement('afterend',b);}}
function openLocationHash(){const match=location.hash.match(/^#site=(.+)$/);if(!match)return;const id=decodeURIComponent(match[1]);if(!features.some(f=>f.properties.id===id))return;const s=instances.university;s.select(id);s.el.scrollIntoView({block:'start'});s.map.invalidateSize();}
window.addEventListener('hashchange',openLocationHash);openLocationHash();
window.studyMaps={instances,occurrences};
})();
